Use the correct configuration directory
KraXen72/crankshaft pull request #4
Opened 2022-04-27 12:25 UTC by Delta-official

updated main.ts so it uses `app.getPath("appData")` instead of `app.getPath("documents")`

2022-04-28 02:43 UTC, Delta-official commented
at least allow linux to use appdata instead of documents, documents is absolutely the wrong place to put stuff like configuration in on linux

2022-04-28 03:28 UTC, Mixaz017 commented
I agree that configuration files definitely shouldn't be stored in the documents folder. I'm not sure about swapper or script paths though. In Linux way, `~/.config` seems ideal, but in Windows, using documents folder for file based customizations is common.

2022-04-28 03:34 UTC, Mixaz017 commented
Deciding where to put stuff based on how easy to access them isn't clever imo, ultimately you'll end up putting everything in the desktop folder. Applications should store files based on how organized they are.

2022-04-28 05:19 UTC, KraXen72 commented
> at least allow linux to use appdata instead of documents, documents is absolutely the wrong place to put stuff like configuration in on linux

i could make it so if there is an appdata folder called Crankshaft, it uses that. Otherwise it falls back to documents. most users already have the settings in documents and it would be a breaking change. This way if you really want to you can use appdata/config on linux.

2022-04-28 05:20 UTC, KraXen72 commented
if you re-implement it this way, i'll merge it

2022-04-28 05:25 UTC, Delta-official commented
ok, i'm gonna implement that

2022-04-28 05:44 UTC, Delta-official commented
done

2022-04-28 05:56 UTC, KraXen72 commented
ok, will review and merge when home. from a quick look on mobile it looks fine.

2022-04-30 07:20 UTC, Delta-official commented
that's a long walk to home

2022-04-30 22:59 UTC, KraXen72 commented
i forgot. i will merge it soon tm when im back from vacation.

2022-05-01 19:08 UTC, KraXen72 requested changes

2022-05-01 19:08 UTC, KraXen72 commented on src/main.ts
> +// Tae - logo for>> the client
revert this, not needed

2022-05-01 19:08 UTC, KraXen72 commented on src/main.ts
> +if (!fs.existsSync(swapperPath)) {
revert this to original, one line state

2022-05-03 07:04 UTC, KraXen72 commented
eh i'mma implement this myself

2022-05-03 07:04 UTC, KraXen72 commented
will give credit dw

2022-05-03 07:16 UTC, KraXen72 commented
fyi, you don't have to explictly type variables as long as the thing that is filling them with content already has a type / is typed correctly (the fs module has typescript types)
![image](https://user-images.githubusercontent.com/21956756/166416563-72ef7eb0-82bb-4fab-b12b-3e43d15e5c65.png)

2022-05-03 07:24 UTC, KraXen72 commented
ok so i tried it an there is a pretty major issue:
the appdata directory  for the app does exist on windows by default, since that's where the installer installs it. so on first boot it would make a settings.json there and then the document settings would never get used.

this would mean everybody has to use appdata to configure, which is not what i want. gonna close this for now, as i don't know about a better option. feel free to reopen if you have an idea.

2022-05-03 07:24 UTC, closed without merging